### ISSUE TITLE
why not in chrome web store?

### ISSUE THREAD

**Issue by MInner** [saboya/youtube-collections#16]
It works as charm, why not to put it in a place where everybody could use it?

**Comment by saboya** [comment]
But I did, it's right there:

https://chrome.google.com/webstore/detail/youtube-collections/pmeoacbdkacmcjgfcadjigglammpehep

**Comment by MInner** [comment]
hmm, that's weird, I could not find it before, thank you for your work! is it possible to change keywords or something so that it would appear in "related" section of [this one](https://chrome.google.com/webstore/detail/video-deck-for-youtube/mpoakikepagdiphlmfaeifpojdmbnegj?hl=en) or [this one](https://chrome.google.com/webstore/detail/subscriptions-grid-for-yo/dcnjhgnfnmijfkmcddcmffeamphmmeed?hl=en-GB)?

**Comment by saboya** [comment]
I'm not sure how or how much I'm able to manipulate the related extensions, so I really don't know how to answer that =P

**Comment by starobots** [comment]
well, dude it's a great work!
utb delete that feature, and even I can't find the channel I'd subscribed.
And can I suggest a feature? could we have a page which for the collection?
I mean when I click the collection icon it will shows the new upload video of this collection on the page.
O/ Thanks alot dude. Really useful for me.

**Comment by saboya** [comment]
Thanks for the feedback, I'm glad you like the exxtension! I'll have to look into that, but I'm kind of busy at the moment, so don't hold your breath.

Also, to keep things more organized, could you open a different issue for this feature requesst? Thanks :)
